# Generated by Django 5.2 on 2025-05-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_credit_number_customercomplaint_number_return_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
