# Generated by Django 5.2 on 2025-05-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_return_authorized'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
