# Generated by Django 5.2 on 2025-05-20 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_credit_status_customercomplaint_status_return_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='category',
        ),
        migrations.AddField(
            model_name='case',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='case',
            name='customer_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='is_scrap',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='process.category'),
        ),
    ]
