# Generated by Django 5.2 on 2025-05-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_remove_case_category_case_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='description',
        ),
        migrations.AddField(
            model_name='case',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
