# Generated by Django 5.2 on 2025-05-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_remove_case_description_case_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='call_tags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='return',
            name='carrier_claim_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='carrier_tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='charges',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='return',
            name='est_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='return',
            name='fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='return',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='returns/'),
        ),
        migrations.AddField(
            model_name='return',
            name='payment_method_requested',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Credit Card', 'Credit Card')], default='open', max_length=100),
        ),
        migrations.AddField(
            model_name='return',
            name='replacement_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='replacement_shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='return',
            name='requested_credit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='return',
            name='taxes',
            field=models.BooleanField(default=False),
        ),
    ]
