# Generated by Django 5.2 on 2025-05-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0011_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomplaint',
            name='classification',
            field=models.CharField(choices=[('shipping', 'Shipping'), ('contamination', 'Contamination'), ('irritation', 'Irritation'), ('leaking', 'Leaking'), ('package_issue', 'Package Issue'), ('efficacy', 'Efficacy'), ('expired', 'Expired'), ('cloudy', 'Cloudy'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
