# Generated by Django 5.2 on 2025-05-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0012_customercomplaint_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercomplaint',
            name='category',
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='investigation_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='investigation_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='lot_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='quality_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='quality_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
