# Generated by Django 5.2 on 2025-05-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0013_remove_customercomplaint_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='cases/'),
        ),
        migrations.AddField(
            model_name='case',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='cases/'),
        ),
        migrations.AddField(
            model_name='case',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='cases/'),
        ),
        migrations.AlterField(
            model_name='customercomplaint',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('request_submitted', 'Request Submitted'), ('path_assigned', 'Path Assigned'), ('investigation_in_progress', 'Investigation In Progress'), ('resolution', 'Resolution'), ('closed', 'Closed')], default='open', max_length=100),
        ),
    ]
