# Generated by Django 5.2 on 2025-05-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0014_case_file1_case_file2_case_file3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='case',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='case',
            name='file3',
        ),
        migrations.AddField(
            model_name='case',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='cases/'),
        ),
        migrations.AddField(
            model_name='case',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='cases/'),
        ),
        migrations.AddField(
            model_name='case',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='cases/'),
        ),
    ]
