# Generated by Django 5.2 on 2025-05-22 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0016_rename_investigation_completed_customercomplaint_time_closed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercomplaint',
            old_name='time_closed',
            new_name='closed_at',
        ),
        migrations.RenameField(
            model_name='customercomplaint',
            old_name='time_investigation_in_progress',
            new_name='investigation_in_progress_at',
        ),
        migrations.RenameField(
            model_name='customercomplaint',
            old_name='time_path_assigned',
            new_name='path_submitted_at',
        ),
        migrations.RenameField(
            model_name='customercomplaint',
            old_name='time_request_submitted',
            new_name='request_submitted_at',
        ),
        migrations.RenameField(
            model_name='customercomplaint',
            old_name='time_resolution',
            new_name='resolution_at',
        ),
    ]
