# Generated by Django 5.2 on 2025-05-22 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0017_rename_time_closed_customercomplaint_closed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercomplaint',
            old_name='path_submitted_at',
            new_name='path_assigned_at',
        ),
    ]
