# Generated by Django 5.2 on 2025-05-22 23:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0018_rename_path_submitted_at_customercomplaint_path_assigned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercomplaint',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
