# Generated by Django 5.2 on 2025-05-28 21:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0021_case_created_by_credit_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercomplaint',
            name='lot_number',
        ),
        migrations.RemoveField(
            model_name='customercomplaint',
            name='sku',
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='death',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='enduser_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='enduser_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='enduser_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='enduser_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='hospitalization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='life_threatening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='path',
            field=models.CharField(blank=True, choices=[('path1', 'Path 1: 29, 33 – Customer Resolution (Customer Service or Sales); 24 – FDA Report Assessment (QA); 26, 27 – Trend Check (QA);25, 28, 30 to 32 – QA Investigation'), ('path2', 'Path 2: 29, 33 – Customer Resolution (Customer Service or Sales); 26-27 – Trend Check (QA); 25, 28, 30 to 32 – QA Investigation.'), ('path3', 'Path 3: 29, 33 – Customer Resolution (customer service or sales); 26, 27 – Trend Verification (QA); Notify Vendor (Purchasing)'), ('path4', 'Path 4: 29, 33 – Customer Resolution (Customer Service or Sales); 26, 27 – Trend Verification (QA); 28 and 31, 32 – Incident Investigation (Customer Service or Sales/Shipping)'), ('path5', 'Path 5: 29, 33 – Customer Resolution (Customer Service or Sales); 24 – FDA Report Evaluation (QA); 26, 27 – Trend Check (QA), Notify Vendor (QA or Purchases).')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='reported_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
