# Generated by Django 5.2 on 2025-05-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0022_remove_customercomplaint_lot_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomplaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint/'),
        ),
    ]
