# Generated by Django 5.2 on 2025-05-28 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0023_customercomplaint_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercomplaint',
            name='reported_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
