# Generated by Django 5.2 on 2025-05-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0024_alter_customercomplaint_reported_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomplaint',
            name='disposition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
