# Generated by Django 5.2 on 2025-05-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0025_customercomplaint_disposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercomplaint',
            name='enduser_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
