# Generated by Django 5.2 on 2025-05-29 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0026_alter_customercomplaint_enduser_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='case',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='case',
            name='image3',
        ),
        migrations.AlterField(
            model_name='customercomplaint',
            name='classification',
            field=models.CharField(blank=True, choices=[('shipping', 'Shipping'), ('contamination', 'Contamination'), ('irritation', 'Irritation'), ('leaking', 'Leaking'), ('package_issue', 'Package Issue'), ('efficacy', 'Efficacy'), ('expired', 'Expired'), ('cloudy', 'Cloudy'), ('other', 'Other')], default='other', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='case_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='process.case')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
