# Generated by Django 5.2 on 2025-05-29 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0027_remove_case_image1_remove_case_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='credit_case',
            new_name='credit',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='return_case',
            new_name='returns',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='scrap_case',
            new_name='scrap',
        ),
        migrations.AddField(
            model_name='item',
            name='cases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='process.case'),
        ),
    ]
