# Generated by Django 5.2 on 2025-05-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0028_rename_credit_case_item_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
