# Generated by Django 5.2 on 2025-06-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0029_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=100),
        ),
    ]
