# Generated by Django 5.2 on 2025-06-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0030_alter_item_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inspected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='inspection_initials',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='wli_item',
            field=models.BooleanField(default=False),
        ),
    ]
