# Generated by Django 5.2 on 2025-06-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0032_item_inspection_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='inspection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
