# Generated by Django 5.2 on 2025-06-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0033_item_received_at_alter_item_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='received_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
